---
language: python
services: docker

env:
  global:
    - ROLE_NAME: sample
  matrix:
    - MOLECULE_DISTRO: ubuntu18
    - MOLECULE_DISTRO: ubuntu16
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME dovry.$ROLE_NAME
  - cd dovry.$ROLE_NAME

script:
  molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
